### ISSUE TITLE
[BUG] `changeCaptureIntervalSeconds` does nothing for `SqlServerStream` streams

### ISSUE THREAD

**Issue by jeppe742** [SneaksAndData/arcane-framework#108]
### Description

normally, the `changeCaptureIntervalSeconds` defines the polling interval for our streams.
This is especially interesting for `SqlServerStream` streams, since they are used to full load tables from the source. 
Right now the `changeCaptureIntervalSeconds` will just be ignored, causing Arcane to reload the tables as fast as possible.

### Steps to reproduce the issue

1. create a stream with `SqlServerStream` type
2. set high value for `changeCaptureIntervalSeconds`
3. Start stream, and watch it go

### Describe the results you expected

We should be able to configure how often `SqlServerStream` streams will try to load tables from the source

**Comment by jeppe742** [comment]
@george-zubrienko @s-vitaliy As discussed for the CRM streams

**Comment by s-vitaliy** [comment]
Discussed with @jeppe742 that I will fix this bug and test it with unit tests. We will try to run integration tests when the stream is actually needed.
